// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoe7RE0smR0dIFUuHuF4Rbjw5W0-P8tSo',
    appId: '1:168420306099:web:0bbe947678062dbcf414c6',
    messagingSenderId: '168420306099',
    projectId: 'controlaschool',
    authDomain: 'controlaschool.firebaseapp.com',
    storageBucket: 'controlaschool.firebasestorage.app',
    measurementId: 'G-5PNLP7T8CJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc3J4Lmf_LkPXCafaAjWAsWIGYp20hpb4',
    appId: '1:168420306099:android:cbe835d7537a1e2df414c6',
    messagingSenderId: '168420306099',
    projectId: 'controlaschool',
    storageBucket: 'controlaschool.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMdRCwfofchsjZGlHkxGH4w76ajK3ezC8',
    appId: '1:168420306099:ios:ed1a5443a46a0b1af414c6',
    messagingSenderId: '168420306099',
    projectId: 'controlaschool',
    storageBucket: 'controlaschool.firebasestorage.app',
    iosBundleId: 'com.example.controlaSchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMdRCwfofchsjZGlHkxGH4w76ajK3ezC8',
    appId: '1:168420306099:ios:ed1a5443a46a0b1af414c6',
    messagingSenderId: '168420306099',
    projectId: 'controlaschool',
    storageBucket: 'controlaschool.firebasestorage.app',
    iosBundleId: 'com.example.controlaSchool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoe7RE0smR0dIFUuHuF4Rbjw5W0-P8tSo',
    appId: '1:168420306099:web:657ec057e18b39d9f414c6',
    messagingSenderId: '168420306099',
    projectId: 'controlaschool',
    authDomain: 'controlaschool.firebaseapp.com',
    storageBucket: 'controlaschool.firebasestorage.app',
    measurementId: 'G-3H4FX5E098',
  );
}
